import { NavBar } from '@/components/Navbar'
import { Container } from '@/styles/pages/init'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Book Wise',
  description: 'Generated by create next app',
}

export default function HomeLayout({ children }: { children: ReactNode }) {
  return (
    <Container>
      <NavBar />
      {children}
    </Container>
  )
}
